### ISSUE TITLE
Robin is now obsolete

### ISSUE THREAD

**Issue by willfalconer** [nib-health-funds/robin#8]
ECR now supports lifecycle policies making robin obsolete

https://aws.amazon.com/blogs/compute/clean-up-your-container-images-with-amazon-ecr-lifecycle-policies/

**Comment by ramesius** [comment]
Been quite the talking point today around here. We will be looking to find a good enough transition for ourselves to the new feature. Thanks for the heads up @willfalconer. For anyone that comes across this repo in the future I think it would be good to flag this feature at the top of the readme.
